### ISSUE TITLE
Somewhat unexpected behaviour when blank lines separate lines of different indentation levels

### ISSUE THREAD

**Issue by tommcdo** [qstrahl/vim-dentures#2]
This recording illustrates the behaviour:

https://asciinema.org/a/9203

We discussed a solution where a block with a deeper indentation would effectively unify the preceding and following blocks of the original indentation level, even when a blank line separates them.

**Comment by qstrahl** [comment]
@tommcdo I believe my latest commits fixed this; would appreciate it if you could confirm... you ninny.

**Comment by tommcdo** [comment]
Seems to be fixed. Thanks!
