### ISSUE TITLE
Leading indentation not included in ai/aI edge case

### ISSUE THREAD

**Issue by tommcdo** [qstrahl/vim-dentures#3]
Sample code:

```
foo {
    one
    two

    three

    four
    five
    six
}
```

`ai` will include trailing whitespace for the "one/two" and "three" blocks, but in the edge case for "four/five/six", the leading whitespace will not be included. Vim's built-in text objects respect this edge case for `ap` and `aw` -- effectively, if there is no trailing whitespace, include leading whitespace.

**Comment by qstrahl** [comment]
I'm pretty sure this isn't a thing any more. Also that you're crazy.

**Comment by tommcdo** [comment]
Just wanted to verify that it looks like it works now. Or maybe it always did and I'm crazy.
