### ISSUE TITLE
i or d?

### ISSUE THREAD

**Issue by nedbat** [qstrahl/vim-dentures#6]
The old mappings used `i` and `I`.  Now they are `d` and `D`, but the docs, both in the README and the doc file, mention `i` and `I`.  Which is it going to be?
Also, why change from `i` to `d`?

**Comment by qstrahl** [comment]
Whoops! It's meant to be `d` now. I thought it was a better mnemonic, given that I'm running with the term `denture`. I had been sort of interchanging the terms `denture` and `indenture`, and I wanted to avoid splintering my terminology.

**Comment by nedbat** [comment]
FWIW, I liked 'i' for 'indent' which is really what it's about.  Also, the downside of automatic vim plugin managers is that there's no way to notice that something like this changed... :(

**Comment by qstrahl** [comment]
Very good points. Do note that I've tried to make it very easy for users to
configure their own mappings, for precisely this reason.

**Comment by chaoren** [comment]
It's important to have a sensible default. As a person who literally just found this plugin, I also think `i` makes more sense than `d`.

**Comment by qstrahl** [comment]
I want to argue that "d for denture" is more intuitive but that seems
stupid when I have two users telling me they find "i for indent" more
intuitive. I'll change it back to "i".

**Comment by qstrahl** [comment]
Closed by b10b495f37b7fa0f7e600055b3e967906f53ef99

**Comment by qstrahl** [comment]
Will update documentation later.
